### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by hungnp194** [zinza-d2-training/thanhpc-react#1]
- Tìm hiểu về Typescript
  - [Spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) 
  - [Destructing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
  - [Object reference and cloning](https://javascript.info/object-copy)
  - [Default Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)
  - [Interface/Type](https://www.typescriptlang.org/docs/handbook/2/objects.html)
  - [Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)
  - [Class](https://www.typescriptlang.org/docs/handbook/2/classes.html)
  - Function type, arrow Func
  - [Advanced Type](https://www.typescriptlang.org/docs/handbook/utility-types.html)

- Bài tập
  - Clone object đã cho, sử dụng spread và destructing. Yêu cầu object và thuộc tính của object đã cloned không có reference tới object cũ [Link](https://codesandbox.io/s/spread-operator-destructing-object-cloning-rjmcy?file=/src/index.js)
  - Viết Model type cho các table database 

![covidtracker](https://user-images.githubusercontent.com/61738572/150733206-6ca87af2-86f0-464e-94b3-ef651c925930.png)

  - Sử dụng các advanced type để viết interface Scalars đại diện cho các kiểu dữ liệu của DB (Ví dụ: Int => number, varchar => string)
  - Sử dụng Scalars để thay thế các type cho model ở trên. Viết các type InsertInput (create api), SetInput (update api) kế thừa từ các model trên. (Ví dụ VaccineInsertInput, VaccineSetInput)

  - Mẫu đã làm [Link](https://www.typescriptlang.org/play#code/C4TwDgpgBAsghiARhAPAFQHxQLxTVAHygDsBXAG3IG4AoGgS2OAgCcAzOAY2gGVO5ycFgGcoAbxpQpUAJJMAXCVIBbZCwA0k6WkYhGwRWVWtN0qABEA9qUTkIhlWtPSAYuUtwDS4xq1SdyhDCwHDKYIrBLIwA5s5S5p4QwPSBEcBRxNF+eBAAHl6RMXFQAGpCnAAWQmkZsdkJzDVF2QH2UIWZNAC+dPqsHNx4KUEhYS70EOQAJqISZpwsEIlTAPqeinwCQsIA2gDkrcGhYHsAusWkYFPLa16bgiL7h6Mn5929TP1c0ADCi8sAVWErHGkxm4myCyWzFWiBAAH5FPAkKh7tt9nJgGcMMUoTc4StSMCWIjYAhkCggawce8GJ92N8oAAhODA0HTUR5ZjEcHPY7smbqKB-aEQKZUlgC2Y9OnMBmDMqcTiMaBciA80QstkTDkQsz0KYbfgPXZ7TFnYrEUJtNGPPZlFiVIQW7JwUjACqWKIALzFRq2dp0xD0TBdZjYLEsyjW0RtxvRZtDbzMwEsMYgpORFNtpvNpxpZmEnuAwn9JoxSeKRcsJZWU3oR2I3Ez5NR8bteYL0jYFHIIBWADcuMqrTCywm85oZaBIKVhyq5MTgHIwO6cFAAAr0TgAaxQipHECFewNe0IUD2VsCZ6IezdHq99F9UxvF4jUfTr72qc-5721ZLL8AOEOsGxCJsIC-HtKH7IclUYZY9gwWgZ2gA8VR4JIVzXXANyEZIBEpYlF1YZdiFXYAMA+OUBl+awmBYEAoDVDVmVZCApT1aQDXHDtK2yK84wDU0HSdFgw2kOCR08ehLGIUs53g0dZOIHZTlpVDhXo9IQBIlgyIo9ct13FAfm0xjj1PP9BKQlDwDo0gGJATCDJwzd8PoQizMcnS9NcyjqK+BV52UuTmPydVwS1DidXBOZuMNKAcwrLFk2kThzP7HikvbXN+LMKSELHHLhJSiSpGgvtBxC5ZeLy1LcUyxRvKcqc6E09DQuIPzsOAIztz3TqZLkyyXz-DKfMYlYrNvQrRzFKDe1gmqYVsmgOpWlSXN6oyPMIobkjknryPdKjZSC352PC7kovYzj4qkbLksTBrsmuRoSvLA5hiOMJyqgCanOmxLnsnSF2IU0H8ukKZoQqSHcrKtKpEBnTmsytr1vs4V2OOwzcIG0z2NGr93sg8bMuBr9+GBYRSbhunkKx2cfnY7aTr63C9vIIngTx07AvlaAJWuyLNTu2LZmyJ7EZe-62HoERgBWQS6v2USqnE5GoEEYIVetNX7XKTX-ogZQ4HochDY151tbAVlhAAdy9EHZZtrXMc0iV+c5zdCYlEm-wVpX9evP9deVmy-zNi3yC-e3hCdl21q94l2fx9z9M8nnvfk0jeqoqQgA)

**Comment by cthanh2310** [comment]
Bài 1: https://codesandbox.io/s/withered-voice-elbv8?file=/src/index.js

**Comment by cthanh2310** [comment]
Bài 2: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoLgGzlAzsgbwChlTkBJcALmRAFcBbAI2gG4SyAVUAT1DBr1mbDqQAiAezpNMEQYxZR2ZZADFMEuANoKRK7gwi4wcBgAcaxqKADmysmK0QwwQ5bDWQN0ck4QAHtpWtvakAGo4CAAWOO6edj6OkHEhPgZyyMFeRAC+RPzQ8EjIAMJQEE4AgiAAJgCqZjVOlDAShD4I5U41APpMPDToWDi4ANoA5JRg4wC6ocidFZC9WoMY2HgT6camZrPzdI3dPato6yNbrkYm5vu5+eCFiCh1uNDIAZC1+GVLENX1I6QFoSYgqYA1NbDTaTcB3FQwYB4MA9ECmDJDDZjcYRKDRHDwsjYYyo9FQrETXH4qCE0gQBhwYCYckXHGRGI0uY+MxwXC4ADuEigkLO0OxVI5dzyYB4ZhebyglAVYEoZjoYGQAF5kAB5BjAMAAHle0AANMhxotjv1xsgAD4Wq3LE7Te0Ww5NZ1acYAPnYMrlyBNUFQzlV6q1yAACjgXFhjQqldAVSA1WA-Q9ILBnsgIggEKAUJ8IN9Sl1IACGp6ICCwWQISyYVNabQyaKKWy8ZKuSo4OqokLgAAvCAizGs7ggPhwntkGBQCQME42DHnJsz+ZgCTL1diibN2ekXADsC4RvYg-zY8SU89GrAHYgJDn-cbnwwOiYTA8HoAN0QBZossL6wtMMz3AGKB5oBNYgMq4YatqeoGoa0GFualrlqOfQ8LaDqYX8KyuvhHrHN6GaQbmAGFqGKZppGMZQHGmCodRICwfBqbqhmBTZsUJS8kWgQljUPxYZWQKwa0dakA27aspePjViB2w3Hsh4LFI4BQD+cnjuuYHzBgbxnvJBktjUSxRKZ+kXm+0qyigAlvEmTEIZGyFGs5EAYU62E2m6BFkcR7qSURvr+o5pSCbR7naoxzGGt5rl0dx7C8UUTlaR4PAfMJpa-FUtRVs0IDST4elrnZhk+GibhmeK7IElyDmBiU2U6SlcW6vqXkdTwvlYb0AX4X54WBaRXrTBRUXtXQ2k8LFXGIdGsbAPGc0LV1y08Y8fFQYgoBaMAEggHlXyiWWfwSdWtYVWOVWvjVKgIP1PSVXuoEtv+gHdCBikIp+35-odQGjv99lEJReZHS4p3bfRSG9axv1wyAg2ETheGOkNLrY+Mk3YeRkWBjDQEnSAS2I6tTHrSxZPHfDcHJghfpAA

**Comment by hungnp194** [comment]
> Bài 1: https://codesandbox.io/s/withered-voice-elbv8?file=/src/index.js
Em có thể viết theo cách ngắn gọn hơn như thế này
```
const destructed = {
  ...country,
  status: {...country.status},
  vaccines: country.vaccines.map(vaccine => ({...vaccine}))
};
```

**Comment by hungnp194** [comment]
> Bài 2: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoLgGzlAzsgbwChlTkBJcALmRAFcBbAI2gG4SyAVUAT1DBr1mbDqQAiAezpNMEQYxZR2ZZADFMEuANoKRK7gwi4wcBgAcaxqKADmysmK0QwwQ5bDWQN0ck4QAHtpWtvakAGo4CAAWOO6edj6OkHEhPgZyyMFeRAC+RPzQ8EjIAMJQEE4AgiAAJgCqZjVOlDAShD4I5U41APpMPDToWDi4ANoA5JRg4wC6ocidFZC9WoMY2HgT6camZrPzdI3dPato6yNbrkYm5vu5+eCFiCh1uNDIAZC1+GVLENX1I6QFoSYgqYA1NbDTaTcB3FQwYB4MA9ECmDJDDZjcYRKDRHDwsjYYyo9FQrETXH4qCE0gQBhwYCYckXHGRGI0uY+MxwXC4ADuEigkLO0OxVI5dzyYB4ZhebyglAVYEoZjoYGQAF5kAB5BjAMAAHle0AANMhxotjv1xsgAD4Wq3LE7Te0Ww5NZ1acYAPnYMrlyBNUFQzlV6q1yAACjgXFhjQqldAVSA1WA-Q9ILBnsgIggEKAUJ8IN9Sl1IACGp6ICCwWQISyYVNabQyaKKWy8ZKuSo4OqokLgAAvCAizGs7ggPhwntkGBQCQME42DHnJsz+ZgCTL1diibN2ekXADsC4RvYg-zY8SU89GrAHYgJDn-cbnwwOiYTA8HoAN0QBZossL6wtMMz3AGKB5oBNYgMq4YatqeoGoa0GFualrlqOfQ8LaDqYX8KyuvhHrHN6GaQbmAGFqGKZppGMZQHGmCodRICwfBqbqhmBTZsUJS8kWgQljUPxYZWQKwa0dakA27aspePjViB2w3Hsh4LFI4BQD+cnjuuYHzBgbxnvJBktjUSxRKZ+kXm+0qyigAlvEmTEIZGyFGs5EAYU62E2m6BFkcR7qSURvr+o5pSCbR7naoxzGGt5rl0dx7C8UUTlaR4PAfMJpa-FUtRVs0IDST4elrnZhk+GibhmeK7IElyDmBiU2U6SlcW6vqXkdTwvlYb0AX4X54WBaRXrTBRUXtXQ2k8LFXGIdGsbAPGc0LV1y08Y8fFQYgoBaMAEggHlXyiWWfwSdWtYVWOVWvjVKgIP1PSVXuoEtv+gHdCBikIp+35-odQGjv99lEJReZHS4p3bfRSG9axv1wyAg2ETheGOkNLrY+Mk3YeRkWBjDQEnSAS2I6tTHrSxZPHfDcHJghfpAA

Đúng hướng nhưng a kỳ vọng áp dụng nhiều type và advanced type đã tìm hiểu nhiều hơn, phần của a chỉ nên là tham khảo cách làm thôi.
@cthanh2310

**Comment by cthanh2310** [comment]
> > Bài 2: https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoLgGzlAzsgbwChlTkBJcALmRAFcBbAI2gG4SyAVUAT1DBr1mbDqQAiAezpNMEQYxZR2ZZADFMEuANoKRK7gwi4wcBgAcaxqKADmysmK0QwwQ5bDWQN0ck4QAHtpWtvakAGo4CAAWOO6edj6OkHEhPgZyyMFeRAC+RPzQ8EjIAMJQEE4AgiAAJgCqZjVOlDAShD4I5U41APpMPDToWDi4ANoA5JRg4wC6ocidFZC9WoMY2HgT6camZrPzdI3dPato6yNbrkYm5vu5+eCFiCh1uNDIAZC1+GVLENX1I6QFoSYgqYA1NbDTaTcB3FQwYB4MA9ECmDJDDZjcYRKDRHDwsjYYyo9FQrETXH4qCE0gQBhwYCYckXHGRGI0uY+MxwXC4ADuEigkLO0OxVI5dzyYB4ZhebyglAVYEoZjoYGQAF5kAB5BjAMAAHle0AANMhxotjv1xsgAD4Wq3LE7Te0Ww5NZ1acYAPnYMrlyBNUFQzlV6q1yAACjgXFhjQqldAVSA1WA-Q9ILBnsgIggEKAUJ8IN9Sl1IACGp6ICCwWQISyYVNabQyaKKWy8ZKuSo4OqokLgAAvCAizGs7ggPhwntkGBQCQME42DHnJsz+ZgCTL1diibN2ekXADsC4RvYg-zY8SU89GrAHYgJDn-cbnwwOiYTA8HoAN0QBZossL6wtMMz3AGKB5oBNYgMq4YatqeoGoa0GFualrlqOfQ8LaDqYX8KyuvhHrHN6GaQbmAGFqGKZppGMZQHGmCodRICwfBqbqhmBTZsUJS8kWgQljUPxYZWQKwa0dakA27aspePjViB2w3Hsh4LFI4BQD+cnjuuYHzBgbxnvJBktjUSxRKZ+kXm+0qyigAlvEmTEIZGyFGs5EAYU62E2m6BFkcR7qSURvr+o5pSCbR7naoxzGGt5rl0dx7C8UUTlaR4PAfMJpa-FUtRVs0IDST4elrnZhk+GibhmeK7IElyDmBiU2U6SlcW6vqXkdTwvlYb0AX4X54WBaRXrTBRUXtXQ2k8LFXGIdGsbAPGc0LV1y08Y8fFQYgoBaMAEggHlXyiWWfwSdWtYVWOVWvjVKgIP1PSVXuoEtv+gHdCBikIp+35-odQGjv99lEJReZHS4p3bfRSG9axv1wyAg2ETheGOkNLrY+Mk3YeRkWBjDQEnSAS2I6tTHrSxZPHfDcHJghfpAA
> 
> Đúng hướng nhưng a kỳ vọng áp dụng type và advanced type đã tìm hiểu nhiều hơn, phần của a chỉ nên là tham khảo cách làm thôi. @cthanh2310

Em đọc cảm giác cũng hiểu tương đối nhưng mà không biết làm cách nào khác anh ạ.

**Comment by cthanh2310** [comment]
Những thứ em hiểu về typescript:
- Default type: 
   + Thông dụng: string, number, boolean, object. Với object thì các property có ký tự ? --> Có nghĩa là không bắt buộc, khi khai báo có thể có hoặc không, với readonly: không được thay đổi.
   + Với Union Types: cho phép giá trị có thể là kiểu dữ liệu này hoặc kiểu dữ liệu kia
   + Interface: một cách khác để khai báo object type(tương tự khai báo type)
   + Assertions type: chỉ cho trình biên dịch biết type sẽ sử dụng cho một giá trị nhằm mục đích kiểm tra kiểu dữ liệu
   + Literal type: để xác định kiểu kí tự chuỗi được chỉ định sẵn
- Generics: để tạo các funtion , interface, class... có tính linh động, tái sử dụng cao.
- Class: gồm các phần như constructor, thuộc tính và phương thức( tương tự java)
- Utility Types: 
   + Partial<Type>: Cho phép tất cả các properties trong object thành không bắt buộc có (optional)
   + Required<Type>: Ngược với Partial, tất cả các properties trong object bắt buộc phải có
   + Readonly<Type>: Tất cả properties trong object chỉ được khai báo lần đầu, khoong được sửa
   + Record<Keys, Type>: Định nghĩa trước key và type, khi khai báo phải tuân thur theo keys và type được định nghĩa
   + Pick<Type, Keys>: Lấy các properties có sẵn trong một interface đã khai báo từ trước
   + Omit<Type, Keys>: Ngược lại với pick, Lấy các properties có sẵn trong một interface đã khai báo từ trước nhưng trừ ra các properties bị Omit.
   + Exclude<UnionType, ExcludedMembers>: Loại trừ các properties đã có trong UnionType
   + Extract<Type, Union>: Lấy các properties có ở cả Type và Union
   + NonNullable<Type>: loại trừ các properties có giá trị null hoặc undefined.
 * Em chưa hiểu phần generics lắm, và chưa quen syntax lắm nhưng em nghĩ là join vào code react project code cho quen syntax được rồi anh ạ
